# Form implementation generated from reading ui file 'television_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from television import Television
tv = Television()

class Ui_Television(object):

    """
    Represents the user interface for a television application.

    This class is used to define the structure and layout of the GUI for a
    television-like interface, primarily created using PyQt framework. It
    manages the overall window, frames, labels, buttons, menu bar, and
    status bar, organizing them in a grid layout for functional use.

    The interface includes:
    - A central widget to contain all elements
    - A decorative frame
    - A centered label, presumably for content display
    - A grid layout with functional buttons (e.g., volume, power)
    - Menu and status bars for additional controls or information
    """

    def setupUi(self, Television)-> None:
        Television.setObjectName("Television")
        Television.resize(511, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Television.sizePolicy().hasHeightForWidth())
        Television.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=Television)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 20, 401, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(100)
        self.frame.setMidLineWidth(100)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 340, 321, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)
        Television.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Television)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 511, 26))
        self.menubar.setObjectName("menubar")
        Television.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Television)
        self.statusbar.setObjectName("statusbar")
        Television.setStatusBar(self.statusbar)

        self.retranslateUi(Television)
        QtCore.QMetaObject.connectSlotsByName(Television)

    def retranslateUi(self, Television) -> None:
        _translate = QtCore.QCoreApplication.translate
        Television.setWindowTitle(_translate("Television", "Television"))
        self.label.setText(_translate("Television", "The TV is off"))
        self.pushButton.setText(_translate("Television", "Volume Down"))
        self.pushButton_2.setText(_translate("Television", "Volume Up"))
        self.pushButton_3.setText(_translate("Television", "Channel Up"))
        self.pushButton_4.setText(_translate("Television", "Channel Down"))
        self.pushButton_5.setText(_translate("Television", "Power"))
        self.pushButton_6.setText(_translate("Television", "Mute"))

        self.pushButton_5.clicked.connect(self.power_button)
        self.pushButton_2.clicked.connect(self.volume_up_button)
        self.pushButton.clicked.connect(self.volume_down_button)
        self.pushButton_6.clicked.connect(self.mute_button)

    def power_button(self):
        tv.power()
        self.label.setText(tv.get_status())
    def volume_up_button(self):
        tv.volume_up()
        self.label.setText(tv.get_volume())
    def volume_down_button(self):
        tv.volume_down()
        self.label.setText(tv.get_volume())
    def mute_button(self):
        tv.mute()
        self.label.setText(tv.get_muted())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Television = QtWidgets.QMainWindow()
    ui = Ui_Television()
    ui.setupUi(Television)
    Television.show()
    sys.exit(app.exec())
